apiVersion: apps/v1
kind: Deployment
  {{- template "app.metadata" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{include "app.labels" . | indent 6}}
  template:
    metadata:
      labels:
{{include "app.labels" . | indent 8}}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.appName }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appName }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.service.port}}
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.service.port}}
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              memory: "256Mi"  # This is the value to increase
            requests:
              memory: "128Mi"  # This is the value to increase as well
