apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.appName } }
  labels:
    app: { { .Values.appName } }
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { .Values.appName } }
      project: roboshop
  template:
    metadata:
      labels:
        app: { { .Values.appName } }
        project: roboshop
    spec:
      containers:
        - name: { { .Values.appName } }
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.appName }}
          envFrom:
            - configMapRef:
                name: { { .Values.appName } }
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
