apiVersion: apps/v1
kind: Deployment
  {{- template "app.metadata" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{include "app.labels" . | indent 4}}
  template:
    metadata:
      labels:
        {{include "app.labels" . | indent 4}}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.appName }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appName }}
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
