apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cart
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cart
  dataFrom:
   - extract:
       key: cart
