# schema load job for catalogue 
{{- if .Values.schema.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ $.Values.appName }}-schema-{{ . | replace "." "" }}'
spec:
  template:
    spec:
      containers: 
      {{- range $job:= .Values.schema.jobs }}
        - name: {{ $job | replace ".sql" "" | replace ".js" "" }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: "db/{{ $job }}"
          envFrom:
            - configMapRef: 
              name: {{ $.Values.appName }}
      {{- end }} 
      restartPolicy: OnFailure
---

{{- end }}